# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2020
# Haoruo Xiang
# Haoruo Xiang <934786601@qq.com>
# Based on common/Makefile.
#


ifndef CONFIG_SPL_BUILD

obj-y += itop4412_init.o
obj-y += itop4412_interrupt.o
obj-y += cmd_cpsr.o
obj-y += partition.o

endif


